/*
 * bg.c — Background image rendering
 *
 * Responsibilities:
 *   - #include "assets/bg_data.h" which contains: uint16_t bg_pixels[320*240]
 *     (RGB565 pixel array, generated by assets/convert.py from bg.png)
 *   - Declare and implement bg_draw()
 *       Copies bg_pixels[] to the VGA pixel buffer using vga_draw_pixel
 *       or a direct memcpy to VGA_PIXEL_BASE if the layout is contiguous
 *   - bg_draw() is called once during init in main.c before drawing the grid
 *     so the grid is composited on top of the background
 *
 * Notes:
 *   - The background should use dark/muted colors so the grid cells are legible
 *   - If the pixel buffer is not contiguous (due to VGA row stride), use a
 *     row-by-row copy loop with the correct stride formula (y << 9)
 *   - bg.png source lives in assets/; bg_data.h is generated — do not edit it by hand
 *   - If no background image is ready yet, bg_draw() can fill with a solid color
 *     as a placeholder using vga_clear()
 */
